project:
  type: website

website:
  title: "Unicef Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Data 
      - href: about.qmd
        text: About
      - about.qmd
echo: false

format:
  html:
    theme:
      - lux
    css: styles.css
    toc: true
    